### ISSUE TITLE
Showing the section name for an empty section?

### ISSUE THREAD

**Issue by PaddyPatPat** [alphapapa/org-super-agenda#236]
Hi there,  
The past issues have dealt a few times with hiding empty sections/groups. I am wondering if the opposite is possible?

I have grouped NEXT actions for each of my projects, with each project displayed in its own section. Where I see an empty section (no NEXT action) I know that I need to go select a TODO to make into a NEXT action. However at the moment empty sections do not show their name.

I see that there is org-super-agenda-hide-empty-groups which I thought might help but that this is off by default. 

Is there a way that I can have org-super-agenda display the name of an empty section even if it is empty?

**Comment by alphapapa** [comment]
> However at the moment empty sections do not show their name.
> 
> I see that there is org-super-agenda-hide-empty-groups which I thought might help but that this is off by default.

Well, you can see where that option was added in https://github.com/alphapapa/org-super-agenda/commit/fd08d0b5dada524a03eca10d51bebcbba3353e72, discussed in #56 and #77.  If the option is disabled but empty groups aren't being shown, that would seem like a bug, and I would guess that something has changed in a newer version of Org that you may be using, so please share that information.  Maybe @cslux will be able to help debug it.  Thanks.

**Comment by PaddyPatPat** [comment]
Ah yes of course. Thank you @alphapapa (and @cslux). 

To answer your question:
Org mode version 9.6 ( @ /Users/patrick/.emacs.d/elpa/org-9.6/)
GNU Emacs 28.2 (build 1, x86_64-apple-darwin21.6.0, NS appkit-2113.60 Version 12.6 (Build 21G115)) of 2022-09-25

**Comment by cslux** [comment]
I'll try to create a PR with a fix ( 🤞🏽 ) for it in the next couple days.

**Comment by cslux** [comment]
@PaddyPatPat Changing the value of `org-super-agenda-header-properties` to `'(org-super-agenda-header t org-agenda-structural-header t)` should fix it. Worked for me! Better solution would be, of course, to always set this "required" property. See https://github.com/alphapapa/org-super-agenda/pull/237 @alphapapa

**Comment by alphapapa** [comment]
Finally fixed.  Thanks to all.

**Comment by Martinsos** [comment]
Apologies if I got something wrong, but is it possible that this issue is back?

I have org 9.8-pre 1c98731d5, org-super-agenda 1.4-pre c07e354, emacs 29.4., vanilla config, and by default `org-super-agenda-hide-empty-groups` is set to `nil`, however empty groups are not shown (their title is not shown, it is as if that group never existed).

**Comment by alphapapa** [comment]
@Martinsos Sure, it's possible, especially if you're using a pre-release version of Org.  You should probably check its commit history for commits related to the agenda and text properties.  If you can find the problem, you can either propose a change upstream, or here, depending on the details.

**Comment by Martinsos** [comment]
> @Martinsos Sure, it's possible, especially if you're using a pre-release version of Org. You should probably check its commit history for commits related to the agenda and text properties. If you can find the problem, you can either propose a change upstream, or here, depending on the details.

Thanks @alphapapa ! I have to admit I didn't opt-in to using pre-release version conciously -> I started using Elpaca recently and I am still lacking somewhat in knowledge both on its details + also emacs package management in general. I guess it just pulls in the latest release regardless of it being pre-release or "stable" release hm, I might want to make sure it doesn't do that. And thanks for the advice regarding commits, that is probably what I should do. Awesome, thanks again!
